[project]
name = "argx"
version = "0.4.4"
description = "Super-charged argparse for python"
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.9"
authors = [{name = "pwwang", email = "pwwang@pwwang.com"}]
dependencies = [
    "python-simpleconf>=0.9,<1.0",
]

[project.optional-dependencies]
anypath = ["panpath>=0.4,<0.5"]
panpath = ["panpath>=0.4,<0.5"]

[dependency-groups]
dev = [
    "flake8>=7,<8",
    "mypy>=1,<2",
    "pytest>=8,<9",
    "pytest-cov>=6,<7",
    "python-simpleconf[toml]>=0.9,<1.0",
]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[tool.setuptools.package-data]
argx = ["py.typed"]

[tool.mypy]
ignore_missing_imports = true
allow_redefinition = true
disable_error_code = ["attr-defined", "no-redef", "union-attr"]
show_error_codes = true
strict_optional = false

[tool.pytest.ini_options]
addopts = "-vv --cov-config=.coveragerc --cov=argx --cov-report xml:.coverage.xml --cov-report term-missing"
filterwarnings = [
    #"error"
]
console_output_style = "progress"
junit_family = "xunit1"

[tool.black]
line-length = 88
target-version = ['py39', 'py310', 'py311', 'py312']
include = '\.pyi?$'
